// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ATable: typeof import('ant-design-vue/es')['Table']
    BasicTable: typeof import('./../src/components/table/basic/BasicTable.vue')['default']
    CrudTable: typeof import('./../src/components/table/crud/crud-table.vue')['default']
    CRUDTable: typeof import('./../src/components/table/crud/CRUDTable.vue')['default']
  }
}

export { }
